version: "3"
services:
  lnbits:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./deployment/.env:/app/.env
      - ./deployment/data:/app/data
